wso2/cellery-samples

pet-store/backend/components/controller/serve.js
pet-store/backend/components/customers/data/customers.json
pet-store/backend/components/orders/data/orders.json
pet-store/backend/components/orders/serve.js
pet-store/frontend/components/portal/src/components/App.js
pet-store/frontend/components/portal/src/components/Catalog.js
pet-store/frontend/components/portal/src/server/app.js

> Add some user specific logic for Web Cell testing.
> Add few user specific logic to identify the user logged in from the Pet Store Portal UI.
> Get the logged in user from the headers provided by the STS and change the pages and the returned data accordingly. The headers that are required to be forwarded are forwarded by the Portal and Controller.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Implement user specific logic for Orders and Portal

---

.gitignore
pet-store/README.md
pet-store/backend/pet-be.bal
pet-store/frontend/pet-fe.bal

> Updating the Pet Store Cell files to the latest Cellery Syntax
> Support the Web Cell and update the Cell file
> The Cell files are updated to match the latest Cellery syntax and the pet-fe Cell Image was added.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Port Pet Store sample Cell files to the latest Cellery Syntax changes

---

hello-world/hello/hello-world.bal

Fix docker image

---

hello-world/hello/hello-world.bal

Change Hello world Cell port

---

README.md
hello-world/hello/hello-world.bal

Improve code quality of Hello World Cell

---

pet-store/frontend/pet-fe.bal

Add VHost for Petstore frontend Cell

---

Makefile
README.md
hello-world-api/Makefile
hello-world-api/README.md
hello-world-api/components/hello-service/Dockerfile
hello-world-api/components/hello-service/hello-service.go
hello-world-api/hello-world-api.bal

> Add cellery hello world rest api sample.

cellery hello world api sample 🎉

---

.travis.yml
Makefile
hello-world-api/Makefile
hello-world-api/components/hello-service/Dockerfile
hello-world-web/Makefile
pet-store/Makefile
pet-store/backend/components/catalog/serve.js
pet-store/backend/components/customers/serve.js
pet-store/backend/components/orders/serve.js
pet-store/frontend/components/portal/src/components/App.jsx
pet-store/frontend/components/portal/src/components/catalog/AddToCartPopup.jsx
pet-store/frontend/components/portal/src/components/catalog/Catalog.jsx
pet-store/frontend/components/portal/src/components/common/state.jsx
pet-store/frontend/components/portal/src/components/orders/CartView.jsx
pet-store/frontend/components/portal/src/components/orders/Orders.jsx
pet-store/frontend/components/portal/src/components/orders/cart.js
pet-store/frontend/components/portal/src/components/user/SignUp.jsx
pet-store/frontend/components/portal/src/index.jsx
pet-store/frontend/components/portal/src/server/app.js
pet-store/frontend/components/portal/src/utils.js

> Add minor improvements to the Pet Store sample.
> Add minor improvements and fix bugs in the Pet Store sample and add Travis.
> Travis .yaml file is added to run builds and verify whether the new PRs are valid. Minor improvements were made to the Pet Store portal and minor bugs in the Microservices were fixed.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> GNU Make 4.1
go1.11 linux/amd64
NPM 6.9.0
Node v9.11.2
> N/A

Add minor improvements to the Pet store

---

README.md

Add travis ci status

---

pet-store/pet-be/components/controller/serve.js
pet-store/pet-be/components/customers/serve.js

> Fix bug in Pet Store User Profile
> Fix bug in Pet Store User Profile
> The bug in the username had been fixed so that the user can be identified properly
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Fix bug in Pet Store User Profile

---

hello-world-api/README.md

> Correct global API name of hello world api sample.

minor fix - correct global api name

---

Makefile
hello-world-api/Makefile
hello-world-api/hello-world-api.bal
hello-world/Makefile
hello-world/hello-world.bal
pet-store/Makefile
pet-store/pet-be/pet-be.bal
pet-store/pet-fe/pet-fe.bal

> Changes version from 0.2.0 to latest

Change version to latest

---

hello-world-api/README.md
hello-world/README.md

Include Ballerina syntax highlighting in .md files

Include Ballerina syntax highlighting in .md files

---

hello-world-api/README.md
hello-world-api/hello-world-api.bal
hello-world/README.md
hello-world/hello-world.bal
pet-store/pet-be-cell-description.md
pet-store/pet-be/pet-be.bal
pet-store/pet-fe-cell-description.md
pet-store/pet-fe/pet-fe.bal

- Update samples to the new syntax

Update samples to the new syntax

---

.travis.yml
pet-store/pet-fe/pet-fe.bal

Update to 0.991.0 Synatx

---

hello-world-api/hello-world-api.bal
hello-world/hello-world.bal
pet-store/pet-be/pet-be.bal
pet-store/pet-fe/pet-fe.bal

> Revert image tags to latest
> Revert image tags to latest
> Revert image tags to latest
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

 Revert all image tags to latest

---

cells/pet-store/pet-be/pet-be.bal
tests/pet-store/pet-be/Dockerfile
tests/pet-store/pet-be/README.md
tests/pet-store/pet-be/io.cellery.test.petstore.be/pom.xml
tests/pet-store/pet-be/io.cellery.test.petstore.be/src/test/java/io/cellery/test/petstore/be/PetBeTest.java
tests/pet-store/pet-be/io.cellery.test.petstore.be/src/test/java/io/cellery/test/petstore/be/utils/HTTPClient.java
tests/pet-store/pet-be/resources/run.sh

> Contains the first cell test for pet-be cell. The testcase asserts the adding an order and retrieving it.

Add pet-be order add and retrieve test case

---

cells/pet-store/pet-be/pet-be.bal
tests/pet-store/pet-be/README.md
tests/pet-store/pet-be/io.cellery.test.petstore.be/src/test/java/io/cellery/test/petstore/be/PetBeTest.java

Modify pet-be sample tests

---

cells/pet-store/README.md
docs/pet-store/test-be-cell.md

> Add pet-be cell testing readme

Add pet-be cell testing readme

---

.travis.yml

> Add docker login to .travis.yml for building test images

Add docker login to .travis.yml

---

src/pet-store/pet-be/catalog/serve.js
src/pet-store/pet-be/controller/serve.js
src/pet-store/pet-be/customers/serve.js
src/pet-store/pet-be/orders/serve.js
src/pet-store/pet-fe/portal/src/serve.js
src/pet-store/pet-fe/portal/src/server/app.js

> Add support for pet-store to gracefully handle SIGTERM signal
> Add support for pet-store to gracefully handle SIGTERM signal
> Add support for pet-store to gracefully handle SIGTERM signal
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Add support for pet-store to gracefully handle SIGTERM signal

---

.travis.yml

Reverts wso2-cellery/samples#50

Revert "Add docker login to .travis.yml"

---

src/pet-store/pet-be/catalog/serve.js
src/pet-store/pet-be/controller/serve.js
src/pet-store/pet-be/customers/serve.js
src/pet-store/pet-be/orders/serve.js
src/pet-store/pet-fe/portal/src/serve.js

> Fix check style issues
> Fix check style issues
> Fix check style issues
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Fix check style issues

---

docs/pet-store/scale-cell.md

Update zero scaling sample readme

Update zero scaling sample readme

---

cells/pet-store/README.md
docs/pet-store/build-and-run.md
docs/pet-store/cell-component-update-and-adv-deployment.md
docs/pet-store/observability.md
docs/pet-store/scale-cell.md
docs/pet-store/test-be-cell.md

> Modify cell update and advanced deployment docs.

modify cell update & adv. deployment docs

---

cells/hello-world-api/hello-world-api.bal
cells/hello-world/README.md
cells/hello-world/hello-world.bal
cells/hipster-shop/ads/ads.bal
cells/hipster-shop/cart/cart.bal
cells/hipster-shop/checkout/checkout.bal
cells/hipster-shop/front-end/front-end.bal
cells/hipster-shop/products/products.bal
cells/pet-store/advanced/load-gen/load-gen.bal
cells/pet-store/advanced/pet-be-auto-scale/pet-be-auto-scale.bal
cells/pet-store/advanced/pet-be-zero-scale/pet-be-zero-scale.bal
cells/pet-store/advanced/pet-be/pet-be.bal
cells/pet-store/pet-be/README.md
cells/pet-store/pet-be/pet-be.bal
cells/pet-store/pet-fe/README.md
cells/pet-store/pet-fe/pet-fe.bal

* Method signature and return values of run function in sdk was updated.
* Updated all sample cells to cater to that change.

Update sample cells with new run function

---

src/pet-store/pet-be/catalog/package-lock.json
src/pet-store/pet-be/catalog/package.json
src/pet-store/pet-be/catalog/serve.js
src/pet-store/pet-be/controller/.eslintrc.json
src/pet-store/pet-be/controller/package-lock.json
src/pet-store/pet-be/controller/package.json
src/pet-store/pet-be/controller/serve.js
src/pet-store/pet-be/customers/package-lock.json
src/pet-store/pet-be/customers/package.json
src/pet-store/pet-be/customers/serve.js
src/pet-store/pet-be/orders/package-lock.json
src/pet-store/pet-be/orders/package.json
src/pet-store/pet-be/orders/serve.js
src/pet-store/pet-fe/portal/package-lock.json
src/pet-store/pet-fe/portal/package.json
src/pet-store/pet-fe/portal/src/server/app.js

> Fix bug in pet store portal API request forwarder.
> Fix bug in pet store portal API request forwarder.
> Fix bug in pet store portal API request forwarder.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Fix bug in pet store portal API request forwarder

---

Makefile
cells/hello-world-api/hello-world-api.bal
cells/hello-world/README.md
cells/hello-world/hello-world.bal
cells/hipster-shop/checkout/checkout.bal
cells/hipster-shop/front-end/front-end.bal
cells/pet-store/advanced/load-gen/load-gen.bal
cells/pet-store/advanced/pet-be-auto-scale/pet-be-auto-scale.bal
cells/pet-store/advanced/pet-be-zero-scale/pet-be-zero-scale.bal
cells/pet-store/advanced/pet-be/pet-be.bal
cells/pet-store/pet-be/README.md
cells/pet-store/pet-be/pet-be.bal
cells/pet-store/pet-fe/README.md
cells/pet-store/pet-fe/pet-fe.bal

Fix wrong docker tags

---

cells/pet-store/pet-be/pet-be.bal
cells/pet-store/pet-be/tests/pet-be-test.bal
cells/pet-store/pet-fe/tests/pet-fe-test.bal

> Add inline tests to pet store

Add inline tests to pet store

---

cells/pet-store/pet-be/tests/pet-be-test.bal
cells/pet-store/pet-fe/tests/pet-fe-test.bal

Fix wrong urls

---

cells/hello-world-api/hello-world-api.bal

> Update hello-world-api docker image name

Update hello-world-api docker image name

---

.github/workflows/notify.yaml

Add hangouts pr notification action

Add hangouts pr notification action

---

src/pet-store/pet-be/catalog/.eslintrc.json
src/pet-store/pet-be/controller/.eslintrc.json
src/pet-store/pet-be/controller/serve.js
src/pet-store/pet-be/customers/.eslintrc.json
src/pet-store/pet-be/orders/.eslintrc.json
src/pet-store/pet-be/orders/serve.js

> Add guest mode header in Pet Store backend services
> Add guest mode header in Pet Store backend services
> Add guest mode header in Pet Store backend services
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Add guest mode header in Pet Store backend services

---

src/todo-api/README.md
src/todo-api/build.sh
src/todo-api/docker/mysql/Dockerfile
src/todo-api/docker/mysql/init-mysql.sql
src/todo-api/docker/todos/Dockerfile
src/todo-api/go.mod
src/todo-api/go.sum
src/todo-api/kubernetes/hack.yaml
src/todo-api/kubernetes/todos.yaml
src/todo-api/main.go

Add todo api sample

---

src/pet-store/pet-be/controller/serve.js
src/pet-store/pet-be/orders/serve.js
src/pet-store/pet-fe/portal/.eslintrc.json
src/pet-store/pet-fe/portal/package-lock.json
src/pet-store/pet-fe/portal/package.json
src/pet-store/pet-fe/portal/src/components/App.jsx
src/pet-store/pet-fe/portal/src/components/common/state.jsx
src/pet-store/pet-fe/portal/src/components/user/SignIn.jsx
src/pet-store/pet-fe/portal/src/index.jsx
src/pet-store/pet-fe/portal/src/serve.js
src/pet-store/pet-fe/portal/src/server/app.js
src/pet-store/pet-fe/portal/src/utils.js

> Add Pet Store Guest Mode
> Add Pet Store Guest Mode
> Add Pet Store Guest Mode
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Add Pet Store Guest Mode

---

cells/todo-service/advanced/README.md
cells/todo-service/advanced/todo-cell-advanced.bal

- Add todo-cell advanced sample

Add todo-cell advanced sample

---

cells/todo-service/README.md
cells/todo-service/advanced/README.md
cells/todo-service/advanced/todo-cell-advanced.bal
cells/todo-service/todo-cell.bal

> Modify todos with PUT definition

Modify todos with PUT definition

---

cells/pet-store/pet-be/pet-be.bal

> run command is called as the first step of the test method so that url resolution via cellery:resolveReference method happens correctly.

modify test to call run first up

---

cells/todo-service/advanced/README.md
cells/todo-service/advanced/mysql/init.sql
cells/todo-service/advanced/todo-cell-advanced.bal

> Add mysql/init.sql inside todos advanced directory since using Ballerina Docker doesn't allow routing to the immediate parent directory 
> Update advanced todos readme

Modify todos sample

---

cells/todo-service/advanced/README.md
cells/todo-service/advanced/todo-cell-advanced.bal

> Implement DB secret data read from env variable in advance todos

Implement db secret data read from env variable in advance todos

---

cells/pet-store/tests/README.md

Add pet-be test readme

---

cells/todo-service/README.md
cells/todo-service/advanced/README.md

Fix todo-cell README

---

docs/pet-store/test-be-cell.md

> Remove ballerina from prerequisites.

Remove ballerina from prerequisites.

---

src/todo-api/main.go

Make Credentials to accept from either env or from a given path

Make Credentials to accept from either env or from a given path

---

cells/todo-service/README.md
cells/todo-service/advanced/README.md
cells/todo-service/advanced/todo-cell-advanced.bal
cells/todo-service/todo-cell.bal

> Fix readme and code comments in todos

Fix readme and code comments in todos

---

.travis.yml
cells/pet-store/tests/README.md

- Update travis to install 1.0.3

Update travis to install Ballerina 1.0.3

---

cells/todo-service/advanced/README.md

Fix README formatting

---

cells/pet-store/pet-be/pet-be.bal
cells/pet-store/pet-be/tests/pet-be-test.bal

Update files for ballerina-1.0.3

---

cells/todo-service/README.md

Fix minor spelling mistake

---

cells/todo-service/README.md
cells/todo-service/advanced/README.md

Fix spelling mistakes

---

docs/pet-store/component-patch-and-adv-deployment.md

Fix small doc issues

---

composites/hello-world/README.md
composites/todo-service/README.md

Minor doc improvements

---

cells/hipster-shop/README.md

Update hipster-shop docs with correct tags

Update hipster-shop docs with correct tags

---

docs/pet-store/test-be-cell.md

> Update pet-be cell testing doc

Update pet-be cell testing doc

---

cells/pet-store/pet-be/README.md
docs/pet-store/test-be-cell.md

> Update pet-be cell testing readmes

Update pet-be cell testing readmes

---

cells/todo-service/README.md
cells/todo-service/advanced/README.md

Fix Minor Doc Issues

---

docs/pet-store/test-be-cell.md

Fix VScode link

---

docs/pet-store/test-be-cell.md

Fix broken link

---

cells/pet-store/pet-be/tests/pet-be-test.bal
tests/pet-store/pet-be/order/src/test/java/io/cellery/test/petstore/be/PetBeTest.java

> temporarily remove get operation for orders

remove orders get operation

---

cells/pet-store/pet-be/tests/pet-be-test.bal
cells/todo-service/advanced/README.md
composites/pet-store/cell-to-composite/README.md
composites/pet-store/composite-to-composite/README.md

> Add workaround for ballerina http client issue. Ballerina client seems to be not working properly when the Content-Type header is set before the payload is set for JSON payloads. The result is that the payload is not sent in the request. To avoid this the order of method calls had been changed.

Add workaround for ballerina http client issue

---

cells/pet-store/pet-be/tests/pet-be-test.bal

> add sleep to pet-be inline test

add sleep to pet-be inline test

---

cells/pet-store/pet-be/tests/pet-be-test.bal

> Add comments to pet-be-test.bal

Add comments to pet-be-test.bal

---

cells/hipster-shop/README.md

Add gcp setup information to hipster-shop sample

Add gcp setup information to hipster-shop sample

---

cells/todo-service/README.md

> Add pv creation instructions for existing setup

Add pv creation instructions for existing setup

---

cells/hello-world-api/Makefile
cells/hello-world/Makefile
cells/hipster-shop/Makefile
cells/pet-store/Makefile
cells/pet-store/advanced/Makefile
cells/todo-service/Makefile
cells/todo-service/README.md
cells/todo-service/todo-cell.bal
composites/hello-world/Makefile
composites/pet-store/Makefile
composites/todo-service/Makefile
composites/todo-service/todo-composite.bal
src/todo-api/kubernetes/todos.yaml

> Fix wrong docker and cellery versions

Fix wrong docker and cellery versions

---

src/pet-store/pet-be/catalog/.eslintrc.json
src/pet-store/pet-be/catalog/package-lock.json
src/pet-store/pet-be/catalog/package.json
src/pet-store/pet-be/catalog/serve.js
src/pet-store/pet-be/controller/.eslintrc.json
src/pet-store/pet-be/controller/package-lock.json
src/pet-store/pet-be/controller/package.json
src/pet-store/pet-be/controller/serve.js
src/pet-store/pet-be/customers/.eslintrc.json
src/pet-store/pet-be/customers/package-lock.json
src/pet-store/pet-be/customers/package.json
src/pet-store/pet-be/customers/serve.js
src/pet-store/pet-be/orders/.eslintrc.json
src/pet-store/pet-be/orders/package-lock.json
src/pet-store/pet-be/orders/package.json
src/pet-store/pet-be/orders/serve.js
src/pet-store/pet-fe/portal/src/components/user/SignUp.jsx

> Add support to validate pet-store service requests
> Add support to validate pet-store service requests
> Add support to validate pet-store service requests
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Add support to validate pet-store service requests

---

README.md
cells/hello-world-api/README.md
cells/hello-world/README.md
cells/hipster-shop/README.md
cells/pet-store/README.md
cells/pet-store/pet-be/README.md
cells/pet-store/pet-fe/README.md
cells/pet-store/tests/README.md
cells/todo-service/README.md
cells/todo-service/advanced/README.md
composites/hello-world/README.md
composites/pet-store/all-in-one-composite/README.md
composites/pet-store/cell-to-composite/README.md
composites/pet-store/composite-to-composite/README.md
composites/todo-service/README.md
docs/pet-store/build-and-run.md
docs/pet-store/component-patch-and-adv-deployment.md
docs/pet-store/observability.md
docs/pet-store/scale-cell.md
docs/pet-store/test-be-cell.md
src/hello-world-api/README.md
src/hello-world/README.md
src/pet-store/README.md
src/todo-api/README.md

Update cellery samples for org change

---

cells/hipster-shop/checkout/checkout.bal
cells/hipster-shop/front-end/front-end.bal
composites/pet-store/cell-to-composite/pet-fe-cell-to-composite.bal
composites/pet-store/composite-to-composite/pet-fe-guest-mode-composite.bal

- Update getReference syntax
- Depends on https://github.com/wso2/cellery/pull/997

Update getReference syntax

---

cells/todo-service/advanced/Makefile

> Fix indentation issue in todo Makefile

Fix indentation issue in todo Makefile

---

cells/todo-service/Makefile

> Add missing make target to push todo cell

Add missing make target to push todo cell

---

cells/pet-store/pet-be/src/pet_be/tests/pet-be_test.bal

> Add assertion to pet-be docker test

Add assertion to pet-be docker test

---

cells/pet-store/pet-be/README.md

> Change location of pet-be readme.

Change location of pet-be readme.

---

docs/pet-store/build-and-run.md
docs/pet-store/test-be-cell.md

Update pet-store docs

---

cells/todo-service/README.md
cells/todo-service/advanced/README.md

Update todo-service doc

---

cells/pet-store/pet-be/src/pet_be/tests/pet-be_test.bal

Modify pet-be tests

---

cells/todo-service/advanced/README.md

> Fix wrong image name in readme

Fix wrong image name in readme

---

composites/todo-service/todo-service-ingress.yaml

Reverts wso2/cellery-samples#167

Revert "Update todo-service-ingress.yaml"

---

cells/todo-service/README.md
cells/todo-service/advanced/README.md
cells/todo-service/pv-local.yaml

Modify todos sample docs

---

composites/todo-service/todo-service-ingress.yaml

> Use the correct port in the ingress definition.

using correct port in the ingres
